apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dmfsupanel
  labels:
    app: dmfsupanel
    service: web
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: dmfsupanel
        service: web
    spec:
      containers:
        - name: dmfsupanel
          image: froger/dmfsu:0.1.5
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dmfsupanel
                  key: mysql-database
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dmfsupanel
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dmfsupanel
                  key: mysql-password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: dmfsupanel
                  key: secret-key-base
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dmfsupanel
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: dmfsupanel
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dmfsupanel
  labels:
    service: web
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - app.dmfsu.org
      secretName: dmfsupanel-tls
  rules:
    - host: app.dmfsu.org
      http:
        paths:
          - path: /
            backend:
              serviceName: dmfsupanel
              servicePort: 80
